package foxiwhitee.FoxEternity.config;

import foxiwhitee.FoxLib.config.Config;
import foxiwhitee.FoxLib.config.ConfigValue;

@Config(name = "FoxEternity", folder = "Fox-Mods")
public class FEConfig {

    @ConfigValue(category = "Collectors.Basic", name = "ticks", desc = "How many ticks will it take to generate the resource? (1 sec = 20 ticks)")
    public static int neutronCollectorBasicTicks = 6000;

    @ConfigValue(category = "Collectors.Basic", name = "production", desc = "Resource generated by the collector. Write in the format <modId:name.meta:count>")
    public static String neutronCollectorBasicProduction = "<Avaritia:Resource.2>";


    @ConfigValue(category = "Collectors.Advanced", name = "ticks", desc = "How many ticks will it take to generate the resource? (1 sec = 20 ticks)")
    public static int neutronCollectorAdvancedTicks = 5000;

    @ConfigValue(category = "Collectors.Advanced", name = "production", desc = "Resource generated by the collector. Write in the format <modId:name.meta:count>")
    public static String neutronCollectorAdvancedProduction = "<Avaritia:Resource.3:2>";


    @ConfigValue(category = "Collectors.Hybrid", name = "ticks", desc = "How many ticks will it take to generate the resource? (1 sec = 20 ticks)")
    public static int neutronCollectorHybridTicks = 4000;

    @ConfigValue(category = "Collectors.Hybrid", name = "production", desc = "Resource generated by the collector. Write in the format <modId:name.meta:count>")
    public static String neutronCollectorHybridProduction = "<Avaritia:Resource.4>";


    @ConfigValue(category = "Collectors.Ultimate", name = "ticks", desc = "How many ticks will it take to generate the resource? (1 sec = 20 ticks)")
    public static int neutronCollectorUltimateTicks = 2500;

    @ConfigValue(category = "Collectors.Ultimate", name = "production", desc = "Resource generated by the collector. Write in the format <modId:name.meta:count>")
    public static String neutronCollectorUltimateProduction = "<Avaritia:Resource.4>";


    @ConfigValue(category = "Collectors.Quantum", name = "ticks", desc = "How many ticks will it take to generate the resource? (1 sec = 20 ticks)")
    public static int neutronCollectorQuantumTicks = 1000;

    @ConfigValue(category = "Collectors.Quantum", name = "production", desc = "Resource generated by the collector. Write in the format <modId:name.meta:count>")
    public static String neutronCollectorQuantumProduction = "<Avaritia:Resource_Block>";


    @ConfigValue(category = "Synthesizer", name = "stackLimit", max = "64", desc = "Maximum number of collectors that fit in 1 slot")
    public static int neutronSynthesizerStackLimit = 64;
}
